services:
  postgres:
    image: postgres:16-alpine
    container_name: hotel_db
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    networks:
      - hotel-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hotel.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - hotel-network

volumes:
  postgres_data_v2:

networks:
  hotel-network:
    driver: bridge